### ISSUE TITLE
[BUG] Needs update! Not working in v26.09.2

### ISSUE THREAD

**Issue by DerDemystifier** [hafatsat-anki/anki_Inspector_in_a_new_window#1]
```
Anki 26.09.2 (bb0dd6d1) (ao)
Python 3.13.15 Qt 6.11.2 PyQt 6.11.0
Platform: Windows-11-10.0.26200-SP0

When loading Inspector in a new window mizmu addons:
Traceback (most recent call last):
  File "D:\a\anki\anki\out\installer\build\anki\windows\visualstudio\x64\Release\app_packages\aqt\addons.py", line 247, in loadAddons
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\404783644\__init__.py", line 1, in <module>
    from . import inspector
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\404783644\inspector.py", line 112, in <module>
    main()
    ~~~~^^
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\404783644\inspector.py", line 108, in main
    inspector = Inspector('', mw)
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\404783644\inspector.py", line 35, in __init__
    Qt.LeftDockWidgetArea|Qt.RightDockWidgetArea|Qt.BottomDockWidgetArea)
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Qt' has no attribute 'LeftDockWidgetArea'. Did you mean: 'DockWidgetArea'?
```
